import {Well} from './well';

export const WELLS: Well[] = [
    { id: 12, name: 'ABC_Well' },
    { id: 13, name: 'ClaritiDemoSimulationWell' },
    { id: 14, name: 'ClaritiTestHalliburton_123Long' },
    { id: 15, name: 'ClaritiWell02' },
    { id: 16, name: 'ClaritiWell04' },
    { id: 17, name: 'Clariti_New_Well' },
    { id: 18, name: 'DSRTTEST' },
    { id: 19, name: 'DeadWell01' },
    { id: 20, name: 'Demo_Well_253' },
    { id: 21, name: 'EN-RICE-A-155-94-0310H-2' },
    { id: 22, name: 'EN-RICE-A-155-94-0310H-6' },
    { id: 23, name: 'Erle-2' },
    { id: 24, name: 'HAL_America_Well' },
    { id: 25, name: 'Installer_150_Well' },
    { id: 26, name: 'Installer_Demo_Well' },
    { id: 27, name: 'Mobile_Test_Well1' },
    { id: 28, name: 'Mobile_Test_Well2' },
    { id: 29, name: 'NewInstaller_Well' },
    { id: 30, name: 'New_ODEX_Test_Well_11052022' },
    { id: 31, name: 'New_ODEX_Well_40' },
    { id: 32, name: 'Northsea_Well' },
    { id: 33, name: 'Odex_Well_40' },
    { id: 34, name: 'Offline_Sensor_Test' },
    { id: 35, name: 'RTS_Schematics_Well' },
    { id: 36, name: 'StgKurdamir' },
    { id: 37, name: 'TestWell122' },
    { id: 38, name: 'TestWell_127820' },
    { id: 39, name: 'TestWell_128644' },
    { id: 40, name: 'Two_Stress_Test' },
    { id: 41, name: 'Vida-1' },
   
]